FROM node:16-alpine AS build

ARG API_URL="'http://localhost:8080/api'"

WORKDIR /app
COPY . .
RUN npm install && \
  sed -i -e "/REACT_APP_API_URL = /c\\REACT_APP_API_URL = ${API_URL}" .env && \
  npm run build --production

FROM nginx:1.23.1-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY ./conf-dev/nginx.conf /etc/nginx/nginx.conf
COPY ./conf-dev/gateway.conf /etc/nginx/gateway.conf
EXPOSE 80